# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: AryaQuest
  labels:
    app: AryaQuest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AryaQuest
  template:
    metadata:
      labels:
        app: AryaQuest
    spec:
      containers:
      - name: AryaQuest
        image: <REGISTRY>/<NAMESPACE>/myapp:v0.0.1
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true
        - name: CLOUDANT_USERNAME
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: username
              optional: true
        - name: CLOUDANT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: password
              optional: true
